Ready without second additional task
mmf19144/programming2020 pull request #20
Opened 2020-09-24 06:54 UTC by dj-kostya

Возникла проблема со вторым дополнительным заданием. 

я думал создать массив из ссылок, но такое делать в c++ нельзя. И я не знаю как обеспечить доступ к эл-ту матрицы, так чтобы можно было менять переменные в исходной матрице

2020-09-29 06:13 UTC, kikht requested changes

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +    size_t rowIdx;
Почему rowIdx не константный?

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +    friend std::ofstream &operator<<(std::ofstream &os, const MatrixRow &m) {
Зачем нужна эта копипаста, `std::ofstream` это же наследник `std::ostream` и оператора для него должно быть достаточно.

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +            os << "\n";
Вывод этого перевода строки лучше оставить на совести пользователя, а не навязывать.

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +    const size_t matrixSize;
Раз уж классы строки и столбца разные, то для строки можно не сохранять размер матрицы, а обойтись одним указателем.

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +    size_t colIdx;
почему не константа?

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +            matrix[i] = 0;
такое зануление обычно лучше делать через `memset`

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +                if (m1.matrix[i * m1.size + j] != m2.matrix[i * m2.size + j])
А тут можно `memcmp`

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +                    new_row = true;
тут баг

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +                minor.matrix[(i - new_row) * size + j - new_column] = matrix[i * size + j];
У вас же есть реализованные операторы для доступа к элементам. Зачем вы всюду заново выписываете арифметику индексов?

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +    friend std::ostream &operator<<(std::ostream &os, const Matrix &m) {
А тут можно было бы воспользоваться уже написанным кодом для вывода строки

2020-09-29 06:13 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +    Matrix d = (A + B * (C.T()) + K) * (D.T());
В задании скобки стоят иначе. Странно, что тесты прошли.

2020-09-29 06:22 UTC, dj-kostya commented on dj-kostya/1 Tour/Matrix.cpp
> +    friend std::ofstream &operator<<(std::ofstream &os, const MatrixRow &m) {
Я гуглил перегрузку для fin  и не увидел, что он наследуется

2020-09-29 06:23 UTC, dj-kostya commented on dj-kostya/1 Tour/Matrix.cpp
> +            os << "\n";
Хорошо

2020-09-29 07:55 UTC, dj-kostya commented on dj-kostya/1 Tour/Matrix.cpp
> +    Matrix d = (A + B * (C.T()) + K) * (D.T());
<img src="https://render.githubusercontent.com/render/math?math=(A%20%2B%20B%20\times%20C^T%20%2B%20K)%20\times%20D^T" /> это же тоже самое, что и у меня

2020-09-29 07:57 UTC, dj-kostya commented on dj-kostya/1 Tour/Matrix.cpp
> +    const size_t matrixSize;
Мне для вывода нужен размер

2020-10-06 05:25 UTC, kikht approved these changes

2020-10-06 05:25 UTC, kikht commented on dj-kostya/1 Tour/Matrix.cpp
> +        if (size <= 1 || size < row || size < column || row <= 0 || column <= 0)
Это отличный способ взорвать мозг себе и пользователям своего кода - в части случаев использовать 0-based индексы, а в части - 1-based.

2020-10-06 06:51 UTC, dj-kostya commented on dj-kostya/1 Tour/Matrix.cpp
> +        if (size <= 1 || size < row || size < column || row <= 0 || column <= 0)
Там в задании где-то 0-based, где-то 1-based

2020-10-07 02:31 UTC, merged