added matrix class with addition tast
mmf19144/programming2020 pull request #24
Opened 2020-09-29 09:57 UTC by danya-pixel

2020-10-06 06:19 UTC, kikht requested changes

2020-10-06 06:19 UTC, kikht commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +    size_t size;
Все что может быть константным, должно быть константным.

2020-10-06 06:19 UTC, kikht commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +            tmp[i][j] = (*this)[i][j] + obj[i][j];
Пробелы и отступы

2020-10-06 06:19 UTC, kikht commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +    friend std::ofstream &operator<<(std::ofstream &os, const Matrix &obj) {
Зачем нужна эта перегрузка?

2020-10-06 06:19 UTC, kikht commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +    Matrix operator()(int row, int column) {
Индексы лучше делать size_t. Вообще стоит разобраться с бардаком между использованием знаковых и беззнаковых типов в коде.

2020-10-06 06:19 UTC, kikht commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +    friend std::ifstream &operator>>(std::ifstream &os, Matrix &obj) {
Почему `ifstream`, а не `istream`?

2020-10-06 07:56 UTC, danya-pixel commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +    size_t size;
Исправил

2020-10-13 06:27 UTC, kikht requested changes

2020-10-13 06:27 UTC, kikht commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +        return memcmp(matrix, obj.matrix, size * size * sizeof(int));
Что возвращает `memcmp`?

2020-10-13 06:37 UTC, danya-pixel commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +        return memcmp(matrix, obj.matrix, size * size * sizeof(int));
забыл добавить !, исправил

2020-10-26 14:00 UTC, kikht commented
Окончательную версию надо проверить в nsuts

2020-11-03 04:46 UTC, kikht requested changes

2020-11-03 04:46 UTC, kikht commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +    Matrix (const Matrix& obj) : size(obj.size), matrix(obj.matrix) {
Это приведет к double-free массива в деструкторе.

2020-11-03 04:46 UTC, kikht commented on Sakrarov_Danil/1st_matrix_class/main.cpp
> +        assert(obj.matrix != nullptr);
Надо либо проверить совпадение размеров, либо переаллоцировать массив при необходимости

2020-11-10 05:50 UTC, kikht approved these changes

2020-11-17 03:47 UTC, merged