Патрин_Георгий
mmf19144/programming2020 pull request #25
Opened 2020-10-02 14:00 UTC by GeogrePA

2020-10-06 07:27 UTC, kikht requested changes

2020-10-06 07:27 UTC, kikht commented on Class_Matrix
> +#include <iostream>
Если дать файлу разрешение .cpp, то тут появится подсветка синтаксиса.

2020-10-06 07:27 UTC, kikht commented on Class_Matrix
> +			arr[k] = new int[size];
Зачем аллоцировать память кусочками?

2020-10-06 07:27 UTC, kikht commented on Class_Matrix
> +			arr[k] = new int[size];
Еще хуже то, что этот код скопирован несколько раз.

2020-10-06 07:27 UTC, kikht commented on Class_Matrix
> +					if (arr[i][j] == b.arr[i][j]) {
Тут можно было бы вернуть результат при первом найденном несовпадении

2020-10-06 07:27 UTC, kikht commented on Class_Matrix
> +	void Print (std::ostream& out) const {
Зачем нужна эта функция, когда уже есть `operator<<` ?

2020-10-07 08:33 UTC, GeogrePA commented on Class_Matrix
> +	void Print (std::ostream& out) const {
Я внёс правки, прикрепил файл с кодом ниже

2020-10-13 06:32 UTC, kikht requested changes

2020-10-13 06:32 UTC, kikht commented on fixed_Matrix_class
> +		arr = new int [size];
Тут баг

2020-10-27 02:59 UTC, GeogrePA reviewed
Задача прошла тестирование на NSUts

2020-10-27 02:59 UTC, GeorgePatrin commented on fixed_Matrix_class
> +		arr = new int [size];
Я исправил эту ошибку, всё работает правильно.

2020-10-27 02:59 UTC, GeorgePatrin commented on fixed_Matrix_class
> +
```suggestion
		arr = new int [size * size];

```

2020-11-03 04:51 UTC, kikht approved these changes

2020-12-15 03:54 UTC, merged