1 Matrix
mmf19144/programming2020 pull request #26
Opened 2020-10-04 07:01 UTC by Qishna

1st version of Matrix

2020-10-13 06:37 UTC, kikht requested changes
Вы делаете что-то очень странное. Я не могу быстро понять по коду, чего тут вообще происходит. Напишите, пожалуйста, как вы представляете в памяти матрицу, столбцы и строки. И почему именно так.

2020-10-13 06:37 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +    int** arr;
Почему это public?

2020-10-13 06:37 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +        this->arr = new int* [n];
Зачем выделять под строчку память? Еще и массив указателей.

2020-10-13 06:37 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +        * column;
Что это такое и зачем оно нужно?

2020-10-15 01:52 UTC, Qishna commented
Я создал два класса: матрицы и строки(они же столбцы). Матрица состоит из строк и столбцов. В массиве указателей храню адреса строк и столбцов, массив указателей public, тк нам необходимо обращаться к адресам строк для того, чтобы их изменять. А память самой матрицы храним в массиве.

2020-10-26 14:13 UTC, kikht commented
А чем оправдан тройной расход памяти в этом решении?

Обращаться к адресам строк напрямую не надо. Именно для этих целей вы перегружаете оператор квадратные скобки.

2020-10-26 15:50 UTC, Qishna commented
Если матрицы будут состоять, например, не из int значений, а из каких-нибудь тяжёлых объектов классов, то если на такие матрицы указывать при помощи указателей, то их вес будет занимать гораздо меньше памяти для учёта, но взамен может дать удобный доступ для объектов.

2020-11-03 04:55 UTC, kikht commented
> Если матрицы будут состоять, например, не из int значений, а из каких-нибудь тяжёлых объектов классов, то если на такие матрицы указывать при помощи указателей, то их вес будет занимать гораздо меньше памяти для учёта, но взамен может дать удобный доступ для объектов.

Удобный доступ до объектов обеспечивается правильной реализацией оператора `[]`. Он и так получается максимально легким, там будет только умножение и сложение. Прочитать из памяти значение указателя будет скорее всего дольше. И это никак не амортизируется размером объектов в матрице.

2020-11-07 07:30 UTC, Qishna commented
Обновил матрицы

2020-11-07 07:30 UTC, merged

2020-11-07 09:23 UTC, Qishna commented
test