Add the first task
mmf19144/programming2020 pull request #29
Opened 2020-10-11 06:57 UTC by Clownessa

2020-10-13 07:02 UTC, kikht requested changes

2020-10-13 07:02 UTC, kikht commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +				this->data[i][j] = orig.data[i][j];
всегда пишите скобки

2020-10-13 07:02 UTC, kikht commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +		init(this->n);
довольно опасный код, легко вызвать эту функцию на уже проинициализированной матрице и получить утечку памяти.

2020-10-13 07:02 UTC, kikht commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +		this->n = n;
Такое лучше делать в списке инициализации.

2020-10-13 07:02 UTC, kikht commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +			assert(0);
Если ограничиваться ассертами, то наверное лучше просто `assert(this->n == that.n)`. Сейчас получается как-то половинчато - в релизной сборке будет сообщение, но программа пойдет выполняться дальше и скорее всего упадет.

2020-10-13 07:02 UTC, kikht commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +	void print() {
Почему print/fprint/set - это не операторы?

2020-10-13 07:02 UTC, kikht commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +	srand(time(0));
зачем это?

2020-10-13 07:02 UTC, kikht commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +		init(this->n);
В чем вообще мотивация выноса этого в отдельную функцию?

2020-10-13 07:04 UTC, kikht requested changes

2020-10-13 07:04 UTC, kikht commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +			this->copy(that);
Тут потенциальный double-free. См. https://github.com/mmf19144/programming2020/pull/27/files#r503702785

2020-10-30 08:35 UTC, Clownessa commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +				this->data[i][j] = orig.data[i][j];
В системе давно тесты прошли
2020-10-05 16:30:28 | 550893 | Вариант 1.1.1 (усложнённый) (Матрицы) | MinGW64 C++ 8.1 | AAAAA Баллы: 0 1 1 1 1 = 4

2020-11-03 05:06 UTC, kikht commented
1. Последнее решение от вас в nsuts не компилируется. В предпоследнем исходники не соответствуют тем, что тут. Перебирать все остальные я не буду. Синхронизируйте, пожалуйста, состояние тут и там. 
2. Решение второй задачи надо отправить отдельным PR.

2020-11-10 05:58 UTC, kikht commented on e-tim-clownessa/1_1_Matrix_class.cpp
> +			this->copy(that);
Вот это таки нужно исправить

2020-12-01 06:32 UTC, kikht commented
```
==10235==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x602000000210
    #0 0x4c4b6d in operator delete(void*) (/tmp/tmp.w2l54G6nBu/a.out+0x4c4b6d)
    #1 0x4c8653 in Matrix::clean() /tmp/tmp.w2l54G6nBu/src.cpp:19:4
    #2 0x4c7d95 in Matrix::~Matrix() /tmp/tmp.w2l54G6nBu/src.cpp:65:3
    #3 0x4c6f4d in main /tmp/tmp.w2l54G6nBu/src.cpp:165:2
    #4 0x7fbaf43b60b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16
    #5 0x41c45d in _start (/tmp/tmp.w2l54G6nBu/a.out+0x41c45d)

0x602000000210 is located 0 bytes inside of 8-byte region [0x602000000210,0x602000000218)
allocated by thread T0 here:
    #0 0x4c441d in operator new[](unsigned long) (/tmp/tmp.w2l54G6nBu/a.out+0x4c441d)
    #1 0x4c8307 in Matrix::init(int) /tmp/tmp.w2l54G6nBu/src.cpp:13:14

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/tmp/tmp.w2l54G6nBu/a.out+0x4c4b6d) in operator delete(void*)
==10235==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==10235==ABORTING
```

2020-12-17 10:50 UTC, closed without merging