Create Derivative_1
mmf19144/programming2020 pull request #32
Opened 2020-10-18 08:30 UTC by GeogrePA

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +	virtual void scan(std::string str) = 0;//считывание выражения по строке
было бы лучше принимать тут всюду константную ссылку на строку. Или вообще std::string_view

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +	Number(const Number& other) {
По правилу трех нужно либо определить оператор присвоения, либо (что лучше) использовать стандартные, т.к. они тут вполне подходят.

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +	std::string var;
const

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +		var.clear();
зачем это?

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +		this->num = stoi(str);
Если мы поддерживаем только целые числа, то почему храним их как double?

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +		size_t idx = s.find(s) + var.length() + 4;//индекс первого элемента означивания переменной
Так не прокатит. Представьте означивание `xx <- 10; x <- 20`

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +		if ((int)str[i] > 43 && (int)str[i] < 58)
Как будто специально написано максимально непонятно. Есть же `std::isdigit`

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +		if ((int)str[i] > 43 && (int)str[i] < 58)
На худой конец что-то вроде `c >= '0' && c <= '9'`

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +Expression* choose(std::string str);//хорошо бы сделать эту функцию методом класса, но реализацию
У вас всегда после `choose` сразу вызывается `scan`. Явный признак того, что нужно сделать одну функцию, которая будет делать оба этих действия.

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +class Add :public Expression
У Add, Sub, Mul и Div очень похожие функции scan и одинаковые поля. Возможно будет удобно завести абстрактный класс BinaryExpression

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +		return 1;//если передали переменную
Вот тут магия какая-то. Эта функция возвращает индекс, или что-то еще?

2020-10-26 15:14 UTC, kikht commented on fixed derivative
> +	for (; a - b != 1 || str[i] == '('; i++) {//находим место в строке, где начинается сама операция
Тут что-то не очень понятное происходит. Напишите больше комментариев, пожалуйста.

2020-11-03 05:10 UTC, kikht commented
Я напрочь запутался в том, какой из файлов надо проверять. Оставьте в PR один нужный.

2020-11-03 09:10 UTC, GeogrePA reviewed
> Я напрочь запутался в том, какой из файлов надо проверять. Оставьте в PR один нужный.

Оставил единственный файл в files chenged

Вы просили напомнить: тестировщик NSUts выдаёт ошибку компиляции из-за std::string_view

2020-11-03 09:10 UTC, GeorgePatrin commented on Derivative_1
> +////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Я прикрепил новый файл, там постарался минимизировать количество повторяющихся кусков кода

2020-11-03 09:10 UTC, GeorgePatrin commented on fixed derivative
> +		return 1;//если передали переменную
Она возвращает индекс знака операции, если он есть.
Если строка это переменная или число, то функция возвращает 1 или 0. Индекс операции такие значения принимать не может, поскольку строка начинается с '(', поэтому это корректно.

2020-11-03 09:10 UTC, GeorgePatrin commented on fixed derivative
> +	for (; a - b != 1 || str[i] == '('; i++) {//находим место в строке, где начинается сама операция
написал в новом файле

2020-11-03 09:10 UTC, GeorgePatrin commented on Source.cpp
> +}
Этот код не проходит NSUts, поскольку std::string_view есть в версии с++ не младше 17 года, срабатывает ошибка компиляции
На компьютере всё проходит хорошо

2020-11-03 09:10 UTC, GeorgePatrin commented on fixed derivative
> +	for (; a - b != 1 || str[i] == '('; i++) {//находим место в строке, где начинается сама операция
Первый цикл находит место в строке, когда до основного знака операции не остаётся скобок
Второй цикл просто ищет ближайший знак операции к месту, где остановился предыдущий цикл

2020-11-10 06:03 UTC, kikht commented on fixed derivative
> +		return 1;//если передали переменную
Хоть бы именованные константы под такие выделенные значения завели. И комментарий в коде написал. Ни черта же просто так не понятно.

2020-11-10 06:28 UTC, kikht requested changes

2020-11-10 06:28 UTC, kikht commented on last_version
> +	Variable(Variable& other):var(other.var) {}
`const Variable&`

2020-11-10 06:28 UTC, kikht commented on last_version
> +		size_t idx = str.find(s) + var.length() + 4;//индекс первого элемента означивания переменной
1. Тут потерян пробел, который вы добавили в `s`. Но вам повезло и дальше все работает, т.к. `stoi` проглатывает пробельные символы. 
2. Лучше было бы написать `strlen(" <- ")`. Компилятор справится с тем, чтобы превратить это в константу, а людям не придется догадываться о тайном смысле значения 4.

2020-11-10 06:28 UTC, kikht commented on last_version
> +		return new Add(new Mul(m1->derivative(str), m2), new Mul(m1, m2->derivative(str)));
m1 и m2 будут разрушены дважды. Один раз в деструкторе этого объекта, другой - в деструкторе каждого Mul, порожденного тут.

2020-11-10 06:28 UTC, kikht commented on last_version
> +		return new Div(new Sub(new Mul(m1->derivative(str), m2), new Mul(m1, m2->derivative(str))), new Mul(m2, m2));
Аналогичная проблема с владением объектами

2020-11-10 06:28 UTC, kikht commented on last_version
> +	}//цикл заканчивается, когда до знака операции не остаётся никаких скобок (ничего, переменная или число)
На лишних скобках развалится `((1+1))`.

2020-11-10 06:28 UTC, kikht commented on last_version
> +	std::string s1, s2;
А почему s1 и s2 не `std::string_view`?

2020-11-17 06:22 UTC, kikht commented
Зачем вы каждый раз создаете новый файл? Так очень неудобно смотреть на разницу между итерациями

2020-11-17 06:39 UTC, kikht requested changes

2020-11-17 06:39 UTC, kikht commented on fixed_on_13.11.2020
> +		return shared_ptr<Number> (new Number());//производная от константы - ноль
лучше `std::make_shared<Number>()`

2020-11-17 06:39 UTC, kikht commented on fixed_on_13.11.2020
> +		size_t idx = str.find(s) + var.length() + strlen(" <- ");//индекс первого элемента означивания переменной
Этот `find` может вернуть `std::string::npos` и тогда все сломается

2020-11-24 09:09 UTC, kikht commented
У меня компилируется и в clang 6.0, и в clang 11.0, и в gcc 7.5 с опцией `-std=c++17`. Проверьте настройки компилятора.

2020-12-15 06:04 UTC, kikht commented
У std::exception по стандарту нет конструктора из строки - https://en.cppreference.com/w/cpp/error/exception/exception

2020-12-15 06:06 UTC, kikht commented
Для использование strlen нужно делать `#include <cstring>`

2020-12-17 10:59 UTC, merged