derivative1
mmf19144/programming2020 pull request #34
Opened 2020-10-19 13:12 UTC by lil-il

2020-10-27 05:48 UTC, kikht requested changes

2020-10-27 05:48 UTC, kikht commented on Ilya_prokofev/derivative/Zayci/Source.cpp
> +		size_t i = eval.find(this -> var + " <- ");
Это не сработает на означивании `xx <- 10; x <- 20`

2020-10-27 05:48 UTC, kikht commented on Ilya_prokofev/derivative/Zayci/Source.cpp
> +		if (left_simpl->to_string() == right_simpl->to_string())
Сравнение через to_string конечно будет работать, но лучше бы было реализовать `operator==`

2020-10-27 05:48 UTC, kikht commented on Ilya_prokofev/derivative/Zayci/Source.cpp
> +	virtual Expression* simplification() const
В этом и аналогичных методах других классов куча утечек памяти. `left_simpl` и `right_simpl` нужно удалить, если они не потребовались. Если использовать `std::unique_ptr`, то жизнь станет сильно проще.

2020-10-27 05:48 UTC, kikht commented on Ilya_prokofev/derivative/Zayci/Source.cpp
> +		catch (invalid_argument)
Обычная логика на исключениях - это плохо. Бросание исключения - медленная операция, к ней стоит прибегать в редких ситуациях (ошибках). Тут же запросто можно проверить число ли это с помощью `std::isdigit`

2020-11-05 12:57 UTC, lil-il commented on Ilya_prokofev/derivative/Zayci/Source.cpp
> +		if (left_simpl->to_string() == right_simpl->to_string())
Не очень понял, как это реализовать. Для каких типов нужно перегружать ==? Не могу придумать, как это сделать для двух произвольных Expression

2020-11-10 07:30 UTC, kikht requested changes

2020-11-10 07:30 UTC, kikht commented on Ilya_prokofev/derivative/Zayci/Source.cpp
> +		int res = (int)stod(x);
Почему не `stoi` ?

2020-11-10 07:30 UTC, kikht commented on Ilya_prokofev/derivative/Zayci/Source.cpp
> +		i += 4 + this->var.length();
вместо магического числа 4 лучше написать `strlen(" -> ")`

2020-11-10 07:30 UTC, kikht commented on Ilya_prokofev/derivative/Zayci/Source.cpp
> +		if (left_simpl->to_string() == right_simpl->to_string())
Тут нужен какой-то вариант для double-dispatch. Вот хорошая статья на тему - https://gieseanw.wordpress.com/2018/12/29/stop-reimplementing-the-virtual-table-and-start-using-double-dispatch/ Там много разных способов разобрано, тут вполне можно воспользоваться самыми простыми из них, тем же dynamic_cast, который у вас уже есть в коде.

2020-11-10 07:30 UTC, kikht commented on Ilya_prokofev/derivative/Zayci/Source.cpp
> +			return new Number(left_number->eval("") + right_number->eval(""));
Тут ошибка. Вы сначала разрушили объекты, а потом вызвали их методы.

2020-12-01 06:45 UTC, kikht commented
санитайзер подтверждает наличие проблем с памятью:
```
=================================================================
==10638==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4c84bb in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:424:9
    #2 0x4c9cec in build_expression(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:559:20
    #3 0x4ca024 in main /tmp/tmp.WE8dKLBpdx/src.cpp:568:20
    #4 0x7fc67ffba0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4d04a3 in Sub::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:207:10
    #2 0x4ca099 in main /tmp/tmp.WE8dKLBpdx/src.cpp:569:25
    #3 0x7fc67ffba0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4c8416 in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:390:10
    #2 0x4c83f0 in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:418:31
    #3 0x4c82ff in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:414:18
    #4 0x4c84da in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:424:17
    #5 0x4c9cec in build_expression(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:559:20
    #6 0x4ca024 in main /tmp/tmp.WE8dKLBpdx/src.cpp:568:20
    #7 0x7fc67ffba0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4c8416 in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:390:10
    #2 0x4c83f0 in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:418:31
    #3 0x4c8316 in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:414:31
    #4 0x4c84da in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:424:17
    #5 0x4c9cec in build_expression(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:559:20
    #6 0x4ca024 in main /tmp/tmp.WE8dKLBpdx/src.cpp:568:20
    #7 0x7fc67ffba0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4cc6c2 in Variable::copy() const /tmp/tmp.WE8dKLBpdx/src.cpp:65:10
    #2 0x4cdde2 in Mul::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:266:55
    #3 0x4ccd23 in Add::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:139:24
    #4 0x4d0513 in Sub::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:207:24
    #5 0x4ca099 in main /tmp/tmp.WE8dKLBpdx/src.cpp:569:25
    #6 0x7fc67ffba0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4cc6c2 in Variable::copy() const /tmp/tmp.WE8dKLBpdx/src.cpp:65:10
    #2 0x4cdde2 in Mul::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:266:55
    #3 0x4ccd89 in Add::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:139:48
    #4 0x4d0513 in Sub::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:207:24
    #5 0x4ca099 in main /tmp/tmp.WE8dKLBpdx/src.cpp:569:25
    #6 0x7fc67ffba0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4cc6c2 in Variable::copy() const /tmp/tmp.WE8dKLBpdx/src.cpp:65:10
    #2 0x4cde4c in Mul::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:266:78
    #3 0x4ccd89 in Add::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:139:48
    #4 0x4d0513 in Sub::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:207:24
    #5 0x4ca099 in main /tmp/tmp.WE8dKLBpdx/src.cpp:569:25
    #6 0x7fc67ffba0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 40 byte(s) in 1 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4c8416 in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:390:10
    #2 0x4c83d9 in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:418:18
    #3 0x4c8316 in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:414:31
    #4 0x4c84da in build(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:424:17
    #5 0x4c9cec in build_expression(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /tmp/tmp.WE8dKLBpdx/src.cpp:559:20
    #6 0x4ca024 in main /tmp/tmp.WE8dKLBpdx/src.cpp:568:20
    #7 0x7fc67ffba0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 32 byte(s) in 2 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4cc04f in Variable::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp
    #2 0x4ccd89 in Add::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:139:48
    #3 0x4d0513 in Sub::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:207:24
    #4 0x4ca099 in main /tmp/tmp.WE8dKLBpdx/src.cpp:569:25
    #5 0x7fc67ffba0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

Indirect leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x4c55ed in operator new(unsigned long) (/tmp/tmp.WE8dKLBpdx/a.out+0x4c55ed)
    #1 0x4cdd04 in Mul::derivative(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const /tmp/tmp.WE8dKLBpdx/src.cpp:266:10
    #2 0x4ccd23 in Add::derivative(std::__cxx11::b [...]

2020-12-17 10:59 UTC, closed without merging