1_tour_matrix
mmf19144/programming2020 pull request #35
Opened 2020-10-19 13:28 UTC by lamer-programmer

2020-10-19 13:30 UTC, lamer-programmer commented on Alexej Huber/Matrix.cpp
> +class Matrix
#include <fstream>
#include <vector>

2020-10-19 13:30 UTC, lamer-programmer commented on Alexej Huber/Matrix.cpp
> +class Matrix
#include <fstream>
#include <vector>

2020-10-19 13:31 UTC, lamer-programmer commented on Alexej Huber/Matrix.cpp
> +class Matrix
#include \<fstream>
#include \<vector>

2020-10-27 05:50 UTC, kikht requested changes

2020-10-27 05:50 UTC, kikht commented on Alexej Huber/Matrix.cpp
> +		data = new int[sz];
тут баг

2020-10-27 05:50 UTC, kikht commented on Alexej Huber/Matrix.cpp
> +		data = new int[sz];
и во всех остальных конструкторах тоже. Видимо вы не запускали программу ни разу. Я не вижу смысла проверять что-то дальше.

2020-10-27 06:08 UTC, closed without merging