Mikhail tyutyulnikov/wolves and rabbits
mmf19144/programming2020 pull request #37
Opened 2020-10-20 05:07 UTC by mtyutyulnikov

2020-10-27 06:45 UTC, kikht requested changes

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +        return p;
`std::make_pair<size_t, size_t>(x, y);`

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +    const size_t animal_type; //0 for wolf, 1 for rabbit, 2 for hyena
Для такого надо завести enum

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +    size_t direction;
Тут тоже enum

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                field[x + y * x_size].clear();
Это лишнее. Конструктор вектора по умолчанию и так создает пустые вектора. Это примитивные типы вроде int имеют неопределенное значение.

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                                      wolves_const[i], 0, i, nullptr);
Кажется, независимая нумерация каждого типа животных может привести к конфликтам при определении старшинства.

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                    if ((*iter)->getAge() < tick - (*iter)->getBirthTick()) {
Как такое может быть?

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +    static Animal *find_eldest_animal_by_type(vector<Animal *> &animals, size_t type) {
вектор стоит передать по константной ссылке, чтобы избежать копирования

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                sort(field[x + y * x_size].begin(), field[x + y * x_size].end());
Тут произойдет не то, что вы хотите. Вектор будет отстортирован по значениям указателей.

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +            for (size_t y = 0; y < y_size; y++) {
Вам будет сильно проще жить если завести переменную `const vector<Animal*>& cur_cell = field[x + y * x_size];`

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +    static Animal *find_eldest_animal_by_type(vector<Animal *> &animals, size_t type) {
А еще эта функция могла бы быть сильно проще, если бы пользовалась отсортированностью списка.

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                            field[x + y * x_size].erase(field[x + y * x_size].end() - 2);
Тут и далее в похожих erase утечка памяти. Вы удаляете указатель из вектора, но не удаляете сам объект. Просто так удалять тут тоже не выйдет, т.к. указатель на объект может быть у какого-нибудь животного, как на родителя.

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                Animal *eldest_hyena = find_eldest_animal_by_type(field[x + y * x_size], 0);
1. Кажется первым должен ходить старший волк или гиена, а не обязательно именно старшая гиена.
2. Остальные гиены тоже могут кого-нибудь съесть.

2020-10-27 06:45 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                            field[x + y * x_size].erase(field[x + y * x_size].end() - 2);
Впрочем все еще хуже. Вы вообще нигде животных не удаляете. В программе ни одного `delete`

2020-10-27 06:49 UTC, mtyutyulnikov commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                    if ((*iter)->getAge() < tick - (*iter)->getBirthTick()) {
В случае, если за текущий тик животное уже передвинулось в другую клетку, и цикл снова встретил это животное

2020-11-03 05:17 UTC, kikht commented
Утечки памяти по прежнему есть. Интерфейсы по прежнему ничего не абстрагируют, повсюду код вроде `if (animal->get_type() == WOLF) { ... }`

2020-11-17 05:02 UTC, kikht requested changes
В целом все хорошо, кроме странного `iter + 1`.

2020-11-17 05:02 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                iter = animals.erase(iter + 1);
Почему `iter + 1`?

2020-11-17 05:02 UTC, kikht commented on m_tyuytulnikov/wolves_and_rabbits.cpp
> +                    iter = std::find(cur_cell.begin(), cur_cell.end(), cur_animal);
Такой подход - ок, но в целом это случай, когда индексы были бы удобнее и быстрее итераторов. От добавления новых животных индекс текущего не изменится в отличие от итератора.

2020-12-15 04:01 UTC, merged