2 Wolves, rabbits
mmf19144/programming2020 pull request #38
Opened 2020-10-26 06:50 UTC by Qishna

2020-10-27 07:29 UTC, kikht requested changes
to be continued

2020-10-27 07:29 UTC, kikht commented on Timur_Garipov/2 Wolves, rabbits.cpp
> +        delete massive;
тут утечка

2020-10-27 07:29 UTC, kikht commented on Timur_Garipov/2 Wolves, rabbits.cpp
> +    int direction;
для такого лучше заводить enum

2020-10-27 07:29 UTC, kikht commented on Timur_Garipov/2 Wolves, rabbits.cpp
> +    void checkBorder(int N, int M) {
Почему это не метод класса coordinates?

2020-10-27 07:29 UTC, kikht commented on Timur_Garipov/2 Wolves, rabbits.cpp
> +    void makeStep() {
Почему бы тут сразу не позвать checkBorder?

2020-10-27 07:29 UTC, kikht commented on Timur_Garipov/2 Wolves, rabbits.cpp
> +    int getStatDie() {
Почему эти четыре метода не в базовом классе?

2020-10-27 07:29 UTC, kikht commented on Timur_Garipov/2 Wolves, rabbits.cpp
> +        reproduction(str);
По заданию в каждой фазе изменяются все животные. А не каждое животное по очереди проходит все фазы.

2020-11-07 07:30 UTC, merged

2020-11-07 09:24 UTC, Qishna commented
test

2020-11-07 11:21 UTC, Qishna commented on Timur_Garipov/2 Wolves, rabbits.cpp
> +        reproduction(str);
А в какой последовательности тогда проходит фаза?