Lamer programmer/matrix 1 tour
mmf19144/programming2020 pull request #39
Opened 2020-10-27 06:14 UTC by lamer-programmer

2020-10-27 06:15 UTC, lamer-programmer commented on Alexej_Huber/Matrix.cpp
> +		data = new int[sz * sz];
Я запускал старый код, и всё проходило нормально. Только что проверил. Не знаю, почему он не жаловался.

2020-10-27 06:47 UTC, kikht commented
Пожалуйста, продолжайте работу в уже созданных PR, а не создавайте на каждую итерацию новые

2020-11-03 05:24 UTC, kikht requested changes

2020-11-03 05:24 UTC, kikht commented on Alexej_Huber/Matrix.cpp
> +			delete[] data;
Это даже не double-free, тут вы `sz` раз пытаетесь одну и ту же память освобождать.

2020-11-03 05:24 UTC, kikht commented on Alexej_Huber/Matrix.cpp
> +		data = new int[sz];
опять тот же баг

2020-11-03 05:24 UTC, kikht commented on Alexej_Huber/Matrix.cpp
> +	const Matrix operator+(const Matrix & A) const
почему возвращается `const Matrix`?

2020-11-03 05:24 UTC, kikht commented on Alexej_Huber/Matrix.cpp
> +	Matrix operator=(const Matrix & A)
Тут надо вернуть ссылку на матрицу

2020-11-03 05:24 UTC, kikht commented on Alexej_Huber/Matrix.cpp
> +	class const_Slice
В чем мотивация? Почему не определить константный `operator[]` в обычном Slice?

2020-11-03 05:38 UTC, lamer-programmer commented on Alexej_Huber/Matrix.cpp
> +	class const_Slice
Компилятор жалуется на неконстантную ссылку в этом случае. У меня не получается скомпилировать код, который Вы написали на семинаре, поэтому пришлось создавать дополнительный класс.

2020-11-03 05:39 UTC, lamer-programmer commented on Alexej_Huber/Matrix.cpp
> +	class const_Slice
Почему стоит label untested? Я сдавал эту задачу в систему и она прошла все тесты.

2020-11-03 06:58 UTC, kikht commented on Alexej_Huber/Matrix.cpp
> +	class const_Slice
Давайте на занятии разберем, в чем тут проблема. Сейчас вышло ужасненько.

2020-11-17 05:08 UTC, kikht approved these changes
Вроде теперь все верно, но с константным слайсом лучше таки разберитесь

2020-12-15 04:01 UTC, merged