Mikhail tyutyulnikov/HashMap
mmf19144/programming2020 pull request #41
Opened 2020-11-01 15:35 UTC by mtyutyulnikov

2020-11-03 06:25 UTC, kikht requested changes

2020-11-03 06:25 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +            while (ptr->next != nullptr) {
Один элемент будет потерян.

2020-11-03 06:25 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        if (data[hash].search({key, val}))
Надо искать только по ключу, а тут поиск по совпадению и ключа, и значения. Или мы тут мультимап делаем? Тогда ситуация с несколькими одинаковыми значениями по одному ключу - валидная, по крайней мере в std::unordered_multimap это так. Иначе мы требуем возможности сравнения от типа значения.

2020-11-03 06:25 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        if ((double) capacity / (double) size >= 0.75) {
кажется тут про rehash_value забыли

2020-11-03 06:25 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +                ++iter;
Кажется, эти две строки лишние и приведут к тому, что мы проскочим один элемент без проверки его ключа.

2020-11-03 06:25 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +    Value *getAllValuesByKey(Key &key) {
Лучше по возможности не заставлять пользователя что-то самостоятельно удалять. Тут можно было бы вернуть std::vector со значениями, а не голый указатель.

2020-11-03 06:25 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +    LinkedList<pair<Key, Value>> *data;
Плохо, что деталь реализации сделана public

2020-11-03 06:25 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        size_t data_id;
От data_id тут можно избавиться. По сути нужны два указателя - на текущую цепочку и на последнюю.

2020-11-03 06:25 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        return map.countValues();
А что этот метод должен делать? Сейчас он по сути копирует хэш-таблицу.

2020-11-03 06:38 UTC, mtyutyulnikov commented on m_tyuytulnikov/hashmap.cpp
> +        if (data[hash].search({key, val}))
Для мультимап используется insert(), позволяющий хранить несколько значений для одного ключа.
Для хэшмап используется replace(), удаляющий все вхождения ключа, прежде чем создавать новую пару

2020-11-03 06:59 UTC, mtyutyulnikov commented on m_tyuytulnikov/hashmap.cpp
> +        return map.countValues();
countUniqueValues() подсчитывает количество уникальных значений в таблице (доп. задание). Для этого формируется хэш-таблица (map) с парами, ключ которых совпадает со значением. Таким образом в новой таблице не будет продублированных значений.

2020-11-17 05:14 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        if (data[hash].search({key, val}))
Это понятно, но обычно мультимап допускает совпадающие пары ключей и значений. Можете убедиться на примере:
```
#include <iostream>
#include <unordered_map>

int main() {
    std::unordered_multimap<int, int> mm;
    mm.emplace(1, 1);
    mm.emplace(1, 1);
    for (const auto& [k, v] : mm) {
        std::cout << k << " " << v << std::endl;
    }
    return 0;
}
```

2020-11-17 05:31 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
>          size_t count = getNumOfElements(key);
`count` теперь не используется. Очень советую собирать программы хотя бы с `-Wunused`, а лучше вообще с `-Wall -Wextra`.

2020-11-17 05:31 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
>          bool operator!=(Iterator const &that) const {
То что `operator==` и `operator!=` реализованы отдельно выглядит очень подозрительно. Почему один не является отрицанием другого?

2020-11-17 05:31 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        it.cur_list = &data[size];
`end_list` и `list_iter` не проинициализированы. Лучше бы сделать у класса `Iterator` такой конструктор, который не позволит чего-нибудь забыть.

2020-11-17 05:31 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        return map.countValues();
Оу, я проглядел, что там оба раза second. Но есть таки два замечания:
1. В качестве значений лучше бы взять что-то гарантированно маленькое, вроде `char`, а не тип значения. 
2. Семантичести тут лучше бы использовать ваш `replace`, т.к. вам тут не нужна мультимапа.

2020-11-24 06:12 UTC, kikht requested changes

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        it.curr = nullptr;
Вот это лишнее. Конструктор по-умолчанию и так зануляет `curr`. Вроде бы это единственное место, для которого нужен friend в классе итератора.

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +    void setHead(Node *new_head) {
Опасный метод. Клиенту надо понимать детали реализации списка, чтобы правильно очистить память. Насколько я вижу, он используется для удаления элементов из списка, и кажется неправильно. Было бы надежнее и удобнее сделать метод remove у итератора списка, который бы удалял текущий элемент и переставлял итератор на следующий.

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        newHashmap.size /= 2;
Для такого было бы удобнее завести метод `swap`.

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +            data[i].clear();
Вот это лишнее. `delete[]` вызовет деструкторы у цепочек, а деструктор LinkedList его очистит

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +            newHashmap.insert((*iter).first, (*iter).second);
Для задания так сойдет, но хорошая реализация тут бы не копировала все элементы, а перенесла существующие элементы цепочек в новые. Еще, если у нас размер таблицы всегда степень двойки, то можно воспользоаться тем свойством, что каждая цепочка распадется ровно на две новые.

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        if ((double) capacity / (double) size >= rehash_value) {
Вместо деления double значений тут, можно было бы в конструкторе один раз посчитать максимальную capacity и тут только сравнить целые.

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +    void setHead(Node *new_head) {
Прочитал использование setHead внимательнее, ошибки там не нашел. В целом понятно, почему код вышел таким. Чтобы поддержать удаление в односвязном списке, итератору придется хранить еще и указатель на указатель на текущий элемент. Так будет чище, но итератор станет больше.

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        insert(key, val);
Тут бы хорошо избавиться от повторного вычисления хэша. Это можно делать через создание отдельных, возможно приватных, методов insert/delete, которые принимают либо хэш, либо вообще указатель на нужную цепочку параметром.

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +        Iterator it (&data[size], &data[size]);
Тут взятие указателя за пределами выделенной памяти. Сама по себе операция валидная. Но вот в конструкторе `Iterator` мы делаем `cur_list->begin()` - и вот так уже нельзя, т.к. `cur_list` не указывает на валидный список.

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +            return end();
У вас довольно много вот таких частных случаев в коде. Лучше стараться писать так, чтобы их не было, а краевые ситуации правильным образом разруливались основным кодом. Это приводит к более надежному коду, т.к. в нем нет отдельных веток, про которые можно забыть. https://medium.com/@bartobri/applying-the-linus-tarvolds-good-taste-coding-requirement-99749f37684a

2020-11-24 06:12 UTC, kikht commented on m_tyuytulnikov/hashmap.cpp
> +    void setHead(Node *new_head) {
Или можно только этим указателем-на-указатель и обойтись. Через него же можно доступиться и до самого элемента тоже.

2020-12-15 04:36 UTC, merged