1_Matrix
mmf19144/programming2020 pull request #46
Opened 2020-11-08 08:10 UTC by Qishna

1_Matrix new version

2020-11-17 07:11 UTC, kikht requested changes

2020-11-17 07:11 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +        delete[] arr;
Тут double-free, т.к. деструктор родительского класса тоже удалит `arr`. Зачем вообще нужен этот класс отдельно?

2020-11-17 07:11 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +    int operator[](int number) {
В задании сказано:
> Любое изменение элементов в строках или столбцах матрицы,полученных соответствующими операциями, приводит к изменению элемента содержащей их матрицы.

Такая реализация строки/столбца этому условию не удовлетворяет.

2020-11-17 07:11 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +    matrix(matrix& c1) {
Зачем нужен этот конструктор по неконстантной ссылке?

2020-11-17 07:11 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +        if (n < 0 || n >= size) throw "�� ���������� ������ � ����� �������";
Есть одна правильная кодировка - utf-8.

2020-11-17 07:11 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +        delete[] arr;
Тут нарушено правило трех и это приведет к ошибкам в управлении памяти.

2020-11-17 07:11 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +        return C;
К слову о правиле трех. Что будет, когда временный объект C разрушится?

2020-11-17 07:11 UTC, kikht commented on Timur_Garipov/1_Matrix.cpp
> +        delete a;
Существование `a` тут ничем не оправданно

2020-11-22 09:40 UTC, Qishna commented on Timur_Garipov/1_Matrix.cpp
> +        return C;
Так как у меня не было конструктора копирование, то новый объект затирался и тем самым передавалось не то что нужно было, исправил

2020-12-01 07:03 UTC, kikht commented
```
src.cpp:175:9: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
        delete a;
        ^
              []
src.cpp:173:18: note: allocated with 'new[]' here
        int* a = new int[size] { 0 };
                 ^
src.cpp:190:9: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
        delete a;
        ^
              []
src.cpp:188:18: note: allocated with 'new[]' here
        int* a = new int[size] { 0 };
                 ^
src.cpp:242:5: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
    delete a;
    ^
          []
src.cpp:240:14: note: allocated with 'new[]' here
    int* a = new int[size] { 0 };
             ^
src.cpp:270:5: warning: 'delete' applied to a pointer that was allocated with 'new[]'; did you mean 'delete[]'? [-Wmismatched-new-delete]
    delete diag;
    ^
          []
src.cpp:261:17: note: allocated with 'new[]' here
    int* diag = new int[N] {k};
                ^
4 warnings generated.
=================================================================
==11204==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x602000000010
    #0 0x4c4c2d in operator delete(void*) (/tmp/tmp.uvohcN3Ur2/a.out+0x4c4c2d)
    #1 0x4c84af in main /tmp/tmp.uvohcN3Ur2/src.cpp:270:5
    #2 0x7f460ee3d0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16
    #3 0x41c51d in _start (/tmp/tmp.uvohcN3Ur2/a.out+0x41c51d)

0x602000000010 is located 0 bytes inside of 8-byte region [0x602000000010,0x602000000018)
allocated by thread T0 here:
    #0 0x4c44dd in operator new[](unsigned long) (/tmp/tmp.uvohcN3Ur2/a.out+0x4c44dd)
    #1 0x4c8318 in main /tmp/tmp.uvohcN3Ur2/src.cpp:261:17
    #2 0x7f460ee3d0b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch (/tmp/tmp.uvohcN3Ur2/a.out+0x4c4c2d) in operator delete(void*)
==11204==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==11204==ABORTING

```

2020-12-15 05:31 UTC, kikht commented
Ошибки по прежнему присутствуют в последней версии. Даю еще неделю и ставлю overdue.

2020-12-15 05:47 UTC, Qishna commented
> Ошибки по прежнему присутствуют в последней версии. Даю еще неделю и ставлю overdue.

какие именно?

2020-12-17 04:24 UTC, merged