hashtable with iterator (open addressing)
mmf19144/programming2020 pull request #52
Opened 2020-11-17 03:52 UTC by danya-pixel

2020-12-01 07:01 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +        return value;
Сюда бы воткнуть `assert(Filled)`

2020-12-01 07:01 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +                return it.getValue();
Ну, нее. Поиск элемента по ключу просмотром всех слотов, это не хэш-таблица, а что-то другое.

2020-12-01 07:01 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +                iter %= size;
В процессе поиска свободного места мы можем наткнуться на совпадающий ключ. Сейчас этот случай обработан только для самого первого элемента в "цепочке".

2020-12-01 07:01 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +    bool Filled;
С таким флагом вы не сможете разделить ситуацию, когда элемент был, но удален от ситуации, когда элемента никогда не было. И в результате при удалении элемента его "цепочка" будет разорвана и часть элементов с тем же хэшем вы никогда не найдете.

2020-12-15 07:19 UTC, kikht requested changes

2020-12-15 07:19 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +        Slot<K, V> &operator*() {
Лучше не отдавать прямо ссылку на слот через итератор. Клиент может сделать setKey и таким образом разломать таблицу. `std::unordered_map` для предотвращения такого дает ссылку на `std::pair<const Key, Val>`

2020-12-15 07:19 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +            if (!table[iter].getDeleted)
скобки потеряны

2020-12-15 07:19 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +                capacity--;
Тут наверное должен быть return. Иначе непонятно, зачем после нахождения ключа мы продолжаем итерации.

2020-12-15 07:19 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +    V &find(const K &getKey) {
Этот метод не сработает в такой ситуации. Пусть есть три ключа с совпадающими хэшами k1, k2, k3. Делаем
```
add(k1);
add(k2);
add(k3);
delete(k2);
find(k3);
```

Получится три слота:
1. filled = true; deleted = false; key = k1
2. filled = false; deleted = true; key = k2
3. filled = true; deleted = false; key = k3

Из цикла мы вывалимся на слоте 2 и до третьего вообще не дойдем.

2020-12-17 10:55 UTC, danya-pixel commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +        Slot<K, V> &operator*() {
А как это можно пофиксить? Использовать std::pair?

2020-12-17 11:12 UTC, kikht commented
Для отладки советую в качестве ключа использовать вот такой класс с вырожденной хэш-функцией:
```
class my_string : public std::string {
};

namespace std {
    template<>
    class hash<my_string> {
    public:
        size_t operator()(const my_string&) const {
            return 0xdeadbeef;
        }
    };
}
```

2020-12-27 13:40 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +        Slot<K, V> &operator*() {
Можно и ваш класс или так `Slot<const K, V>`, или в самом классе сделать ключ константным.

2020-12-27 14:18 UTC, kikht requested changes

2020-12-27 14:18 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +    size_t get_cap() {
У вас стиль оформления нехорошо скачет. То `camelCase`, то `snake_case`. Для одинаковых сущностей стоит использовать один стиль.

2020-12-27 14:18 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +    V &find(const K &getKey) {
Эта же проблема есть в `add_val` и `del_val`

2020-12-27 14:18 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +                return nullptr;
Вот это какое-то бескрайнее зло. Ссылки не должны указывать в никуда. И нормальными средствами такой nullptr определить не получится. Не случайно стандартная хэш-таблица возвращает итератор из метода `find`. Еще можно использовать указатели, для них nullptr понятное и возможное значение.

2020-12-28 08:29 UTC, kikht commented
Без исправления проблемы из https://github.com/mmf19144/programming2020/pull/52#discussion_r543102611 для всех остальных методов я задачу не зачту.

2020-12-28 09:27 UTC, kikht approved these changes
Поздравляю, вы решили действительно сложную задачу.

2020-12-28 09:27 UTC, kikht commented on Sakrarov_Danil/3rd_hashtable/main.cpp
> +            while ((table[iter].getFilled() || table[iter].getDeleted()) && table[iter].getKey() != addKey) {
Тут можно сделать несколько лучше. Если filled слота с совпадающим ключом не нашлось, то элемент лучше положить в первый deleted слот, а не в конец цепочки

2020-12-28 09:31 UTC, merged