Create Vector; 28.11.2020
mmf19144/programming2020 pull request #59
Opened 2020-11-28 14:55 UTC by GeogrePA

2020-12-01 07:29 UTC, kikht requested changes

2020-12-01 07:29 UTC, kikht commented on Vector; 28.11.2020
> +		out << round((data[i]) * 100) / 100 << std::endl;
Для использования round нужен `#include <cmath>`

2020-12-01 07:29 UTC, kikht commented on Vector; 28.11.2020
> +			throw std::exception("удаление по некорректному индексу");
У `std::exception` по стандарту нет такого конструктора https://en.cppreference.com/w/cpp/error/exception/exception

2020-12-01 08:17 UTC, GeogrePA commented on Vector; 28.11.2020
> +		out << round((data[i]) * 100) / 100 << std::endl;
исправил
ещё было замечание, что я использовал несуществующий по стандарту конструктор std::excaption, это тоже исправил

2020-12-15 07:29 UTC, kikht approved these changes

2020-12-15 07:29 UTC, kikht commented on Vector; 28.11.2020
> +			throw "удаление по некорректному индексу";
Не надо бросать прямо строку. Лучше какой-нибудь std::invalid_argument или еще что-нибудь на выбор - https://en.cppreference.com/w/cpp/error/exception

2020-12-15 07:29 UTC, kikht commented on Vector; 28.11.2020
> +		Vector u(size);
Сойдет, но лучше было бы сделать операцию "на месте" с использованием только одной временной переменной, а не целого массива.

2020-12-15 07:29 UTC, kikht commented on Vector; 28.11.2020
> +	void shift_left(size_t num) {//к сожалению, в с++ остатки почему-то бывают отрицательными, поэтому для сдвига
Просвещайтесь - https://en.wikipedia.org/wiki/Modulo_operation

2020-12-17 12:24 UTC, merged