4 task (DFA&&NFA) Without additional tasks
mmf19144/programming2020 pull request #61
Opened 2020-11-29 14:15 UTC by dj-kostya

2020-12-01 06:16 UTC, kikht requested changes

2020-12-01 06:16 UTC, kikht commented on dj-kostya/4 Tour/main.cpp
> +    size_t statesCnt = 0;
Почему кишки класса торчат в public?

2020-12-01 06:16 UTC, kikht commented on dj-kostya/4 Tour/main.cpp
> +    std::set<unsignedSet > endStates;
rule of thumb: если не нужна сортированность коллекции, то лучше использовать `std::unordered_`

2020-12-01 06:16 UTC, kikht commented on dj-kostya/4 Tour/main.cpp
> +    std::set<unsignedSet > endStates;
Вообще, std::set в качестве ключа это довольно смело. Это весьма толстая структура данных, сравнения и хэширование для нее - тяжелые операции.

2020-12-01 06:47 UTC, dj-kostya commented on dj-kostya/4 Tour/main.cpp
> +    std::set<unsignedSet > endStates;
unordered_ не получается использовать, он просит написать свой хэш для коллекций, иначе не компилируется ( я пробовал)

set использую потому-что нужна уникальность номеров вершин

2020-12-01 06:48 UTC, dj-kostya commented on dj-kostya/4 Tour/main.cpp
> +    size_t statesCnt = 0;
Исправил, но пришлось дописать функции, которые возвращают указатели на это ( мне нужны они в DFA)

2020-12-20 04:28 UTC, kikht commented on dj-kostya/4 Tour/main.cpp
> +    std::set<unsignedSet > endStates;
Еще один повод не использовать множества в качестве ключа. Состояния можно представить битовыми масками

2020-12-20 04:29 UTC, kikht commented on dj-kostya/4 Tour/main.cpp
> +    size_t statesCnt = 0;
Прям указатели? Вы их как-то меняете снаружи?

2020-12-20 04:40 UTC, kikht requested changes
Посмотрите еще на замечания вот отсюда https://github.com/mmf19144/programming2020/pull/56 Там то же решение с теми же проблемами. Это загружено раньше, поэтому на него бан не распространяется

2020-12-20 04:40 UTC, kikht commented on dj-kostya/.gitignore
> +.DS_Store
уберите это, или разрешите конфтикты с мастером.

2020-12-20 04:40 UTC, kikht commented on dj-kostya/4 Tour/main.cpp
> +#define unsignedSet std::set<unsigned>
Так делать не надо. Для объявления своего типа лучше всего использовать конструкцию `using unsignedSet = std::set<unsigned>`. На худой конец `typedef`. Но точно не макрос препроцессора.

2020-12-22 17:34 UTC, merged