3 tour Cryball Hashmap
mmf19144/programming2020 pull request #67
Opened 2020-11-30 18:20 UTC by Cryball

2020-12-01 05:08 UTC, kikht commented
Выход за пределы выделенной памяти:
```
=================================================================
==5431==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6180000003a8 at pc 0x0000004cb331 bp 0x7ffd805e29d0 sp 0x7ffd805e29c8
READ of size 8 at 0x6180000003a8 thread T0
    #0 0x4cb330 in LinkedList<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::Iterator::Iterator(LinkedList<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) /tmp/tmp.FxXtICqCwq/src.cpp:310:25
    #1 0x4cb2a8 in LinkedList<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::begin() /tmp/tmp.FxXtICqCwq/src.cpp:370:18
    #2 0x4cb206 in HashMap<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Iterator::Iterator(LinkedList<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, LinkedList<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*) /tmp/tmp.FxXtICqCwq/src.cpp:585:38
    #3 0x4cae9d in HashMap<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::end() /tmp/tmp.FxXtICqCwq/src.cpp:632:18
    #4 0x4c99ea in HashMap<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::countUniqueValues() /tmp/tmp.FxXtICqCwq/src.cpp:644:55
    #5 0x4c7456 in void startProgram<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::istream&, std::ostream&) /tmp/tmp.FxXtICqCwq/src.cpp:673:55
    #6 0x4c6e97 in main /tmp/tmp.FxXtICqCwq/src.cpp:688:9
    #7 0x7fb54ebf90b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16
    #8 0x41c54d in _start (/tmp/tmp.FxXtICqCwq/a.out+0x41c54d)

0x6180000003a8 is located 0 bytes to the right of 808-byte region [0x618000000080,0x6180000003a8)
allocated by thread T0 here:
    #0 0x4c450d in operator new[](unsigned long) (/tmp/tmp.FxXtICqCwq/a.out+0x4c450d)
    #1 0x4c9179 in HashMap<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::HashMap(unsigned long, double) /tmp/tmp.FxXtICqCwq/src.cpp:444:16
    #2 0x4c72f6 in void startProgram<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::istream&, std::ostream&) /tmp/tmp.FxXtICqCwq/src.cpp:658:25
    #3 0x4c6e97 in main /tmp/tmp.FxXtICqCwq/src.cpp:688:9
    #4 0x7fb54ebf90b2 in __libc_start_main /build/glibc-ZN95T4/glibc-2.31/csu/../csu/libc-start.c:308:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /tmp/tmp.FxXtICqCwq/src.cpp:310:25 in LinkedList<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::Iterator::Iterator(LinkedList<std::pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)
Shadow bytes around the buggy address:
  0x0c307fff8020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff8030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff8040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff8050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff8060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c307fff8070: 00 00 00 00 00[fa]fa fa fa fa fa fa fa fa fa fa
  0x0c307fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c307fff8090: ac 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff80a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff80b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c307fff80c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==5431==ABORTING
```

2020-12-15 06:09 UTC, kikht commented
Ошибка по прежнему присутствует. У вас осталась неделя на исправление

2020-12-20 04:22 UTC, kikht requested changes
Впрочем, я зря трачу время. Решение списано вот отсюда https://github.com/mmf19144/programming2020/pull/60

2020-12-20 04:22 UTC, kikht commented on 3 tour Cryball Hashmap
> +Node<K, V>* create_node(K key, V value) {
Это должен быть конструктор.

2020-12-20 04:22 UTC, kikht commented on 3 tour Cryball Hashmap
> +	size_t get_hash(Key& key) {
почему ссылка не константная? в дальнейших методах тоже

2020-12-20 04:22 UTC, kikht commented on 3 tour Cryball Hashmap
> +		HashMap<Key, Value> Hashmapnew(size * 2, rehash_val);
Это сломается при size == 0

2020-12-20 17:36 UTC, Cryball commented
Добрый вечер! Вы поставили метку plagiarism, с чем я не согласен. Во-первых, мое решение выполнено с дополнительной задачей - реализацией мультихешмапа на основе матриц из первой задачи и взятия хеша от матрицы. Во-вторых, мы немного обсуждали реализацию некоторых частей, но при этом каждый из нас старался писать по-своему, не понимаю почему стоит плагиат.

2020-12-22 07:03 UTC, kikht commented
Хорошо, тут еще все не настолько плохо.

2020-12-22 07:05 UTC, kikht commented
При компиляции куча предупреждений вида:
```
src.cpp:403:40: warning: field 'curr_hash' will be initialized after field 'curr_node' [-Wreorder-ctor]
                        info(_info), info_size(_info_size), curr_hash(_curr_hash), curr_node(_ptr)
```

Это может очень неприятно выстрелить, если при инициализации вы где-нибудь попользуетесь еще не инициализированным полем.

2020-12-28 09:33 UTC, merged