Патрин, конечные автоматы
mmf19144/programming2020 pull request #71
Opened 2020-12-09 13:42 UTC by GeogrePA

2020-12-20 09:33 UTC, kikht requested changes

2020-12-20 09:33 UTC, kikht commented on 0.9.12.2020
> +				advance(i, n);//чтобы не зацикливаться
Кажется тут какая-то путаница. Мы же добавили новые пути не за текущим, а в конец списка. Надо не текущий итератор вперед продвигать, а запомнить исходное положение конца. Ну или вставлять новые пути за текущим, а не в конец.

2020-12-20 09:33 UTC, kikht commented on 0.9.12.2020
> +					goto here;
Не надо использовать goto

2020-12-20 09:33 UTC, kikht commented on 0.9.12.2020
> +			(*i).clear();
Зачем очищать каждый путь самостоятельно? Тут же нет никаких указателей. std::list владеет векторами, которые вы в него положили.

2020-12-20 09:33 UTC, kikht commented on 0.9.12.2020
> +	map<Key, vector<size_t>> tab;//таблица: ключ-текущее сост. и буква перехода, значение-вектор состояний, куда можно перейти
Тут нужны только точечные поиски по ключу. Для таких случаев эффективнее использовать std::unordered_map. Ему понадобится определить не оператор сравнения, а функцию кэширования. Ну или можно воспользоваться стандартным типом для ключа: `using Key = std::pair<size_t, char>`

2020-12-20 14:28 UTC, GeogrePA commented on 0.9.12.2020
> +			(*i).clear();
Потому что мы создаём один объект, а потом его проверяем на несколько слов
когда мы работу с одним словом закончили, у этого объекта в поле путей лежат пути от старого слова
и мы по верх них пытаемся писать ещё и новые
перед работой с новым словом надо чистить пути старого

2020-12-20 14:29 UTC, GeogrePA commented on 0.9.12.2020
> +					goto here;
исправил

2020-12-20 14:29 UTC, GeogrePA commented on 0.9.12.2020
> +				advance(i, n);//чтобы не зацикливаться
исправил

2020-12-20 14:42 UTC, GeogrePA commented on 0.9.12.2020
> +	map<Key, vector<size_t>> tab;//таблица: ключ-текущее сост. и буква перехода, значение-вектор состояний, куда можно перейти
у меня unordered_map даже не распознаётся компилятором, можно я не буду переписывать хэш-таблицу?
я понимаю, что многократное сравнение это долго, но в таких масштабах это не критично, и сейчас это исправлять особо некогда

2020-12-21 08:21 UTC, kikht commented on 0.9.12.2020
> +			(*i).clear();
Для этого достаточно сделать `ways.clear();`

2020-12-21 12:02 UTC, GeogrePA commented on 0.9.12.2020
> +			(*i).clear();
понял, сделал

2020-12-28 09:51 UTC, merged