File crawler. Task 5
mmf19144/programming2020 pull request #73
Opened 2020-12-13 08:20 UTC by mtyutyulnikov

2020-12-20 09:59 UTC, kikht requested changes

2020-12-20 09:59 UTC, kikht commented on m_tyuytulnikov/crawler.cpp
> +            if (page_content[i] == '<' && i + 10 < page_content.size()) {
Я этот кошмар уже в третий раз вижу. Похоже надо ставить ноль всем. Во-первых за плагиат, во-вторых за плагиат плохого кода.

2020-12-20 10:11 UTC, mtyutyulnikov commented on m_tyuytulnikov/crawler.cpp
> +            if (page_content[i] == '<' && i + 10 < page_content.size()) {
Мы (совместно) сравнивали эту функцию с аналогичной, работающей на regex. Эта работает быстрее в разы

2020-12-20 15:50 UTC, kikht commented on m_tyuytulnikov/crawler.cpp
> +            if (page_content[i] == '<' && i + 10 < page_content.size()) {
А еще крэшится. Раз вы всей толпой не смогли написать корректный парсер, то ваш 0 вполне заслужен.

2020-12-22 14:34 UTC, kikht commented
https://github.com/mmf19144/programming2020/pull/62#discussion_r547310487

2020-12-28 06:55 UTC, kikht commented on m_tyuytulnikov/crawler.cpp
> +        while (!file_queue.empty()) {
Вот это обращение к file_queue производится из нескольких потоков и не защищено никаким мьютексом. Возможно есть еще такое, я не смотрел все внимательно.

Еще одна ошибка - сейчас при отсутствии работы тред будет непрерывно проверять условие `threadsWorking()` и таким образом впустую тратить ресурсы процессора. Надо сделать так, чтобы он тем или иным образом засыпал на время, когда для него нет работы. И очень желательно, чтобы просыпался сразу, как только она появилась. Проще всего это сделать через условные переменные.

2020-12-28 09:50 UTC, merged